name: json_extractor
description: A minimal library to extract and flatten JSON values according to a user-specified Map schema.
version: 1.0.1
homepage: https://github.com/mitryp/json_extractor

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
